var config = {};
config.mongoUrl = 'mongodb://fancydiving:simhopp1234@ds059682.mlab.com:59682/fancy';
module.exports = config;
//# sourceMappingURL=config.js.map  
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map 
//# sourceMappingURL=config.js.map